name = "aoc2024"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gladvent = ">= 2.0.2 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[gladvent.2024.3]
pt_1 = 167090022
pt_2 = 89823704
[gladvent.2024.4]
pt_1 = 2593
pt_2 = 1950
[gladvent.2024.5]
pt_1 = 5588
pt_2 = 5331
[gladvent.2024.6]
pt_1 = 4778
pt_2 = 1618
[gladvent.2024.7]
pt_1 = 2654749936343
pt_2 = 124060392153684
[gladvent.2024.8]
pt_1 = 280
pt_2 = 958
[gladvent.2024.9]
pt_1 = 6154342787400
pt_2 = 6183632723350
[gladvent.2024.10]
pt_1 = 760
pt_2 = 1764
